esphome:
  name: timesync-demo

external_components:
  - source: components
    components: [zigbee]

esp32:
  board: esp32-h2-devkitm-1
  framework:
    type: esp-idf

logger:

zigbee:
  id: "zb"
  on_join:
    then:
      - logger.log: "Joined network"

time:
  - platform: zigbee
    id: the_time
    timezone: Europe/London
    update_interval: 90s
    on_time_sync:
      then:
        - logger.log: "Synchronized system clock"
    on_time:
      - seconds: /10
        then:
          - logger.log: "Tick-tock, every 10 seconds"
